const container = document.querySelector('.container')
const title = document.querySelector('.title')
const proBar = document.querySelector('.progress-percent')
const image = document.querySelector('.img')
const audio = document.querySelector('.audio')
const prev = document.querySelector('.prev')
const next = document.querySelector('.next')
const play = document.querySelector('.play')